# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e91df172236cefebd3c7b0d3e596af47"
name = "BeU-app"
application_url = "https://dd-79.dynamicdreamz.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/updated"
  topics = [ "orders/updated" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/update"
  topics = [ "shop/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,read_customers,read_draft_orders,read_inventory,read_locations,read_markets,read_orders,read_products,read_shipping,read_store_credit_accounts,read_themes,write_customers,write_discounts,write_draft_orders,write_locations,write_online_store_navigation,write_orders,write_products,write_store_credit_account_transactions,write_validations"

[auth]
redirect_urls = [ "https://dd-79.dynamicdreamz.com/api/auth" ]

[app_proxy]
url = "https://dd-79.dynamicdreamz.com"
subpath = "scotch-soda"
prefix = "apps"
